### ISSUE TITLE
question?

### ISSUE THREAD

**Issue by hodagreat** [oleghnidets/OHMySQL#14]
## What did you do?

ℹ Please replace this with what you did.  

## What happened instead?

ℹ Actual results. Please replace this with of what happened instead. 

## What did you expect?

ℹ Expected results. Please replace this with what you expected.  

## OHMySQL Environment

- **OHMySQL version:**
- **Xcode version:**
- **Swift version:** *(if applicable, if not remove)*
- **Platform(s) running OHMySQL:**

## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.

**Comment by hodagreat** [comment]
wondering if there is a way to append results of select(mysql) to array in xcode..

**Comment by oleghnidets** [comment]
Hi,
I don't understand what you mean? Please, check documentation and existing API. It is a possibility to get an array of SELECT.

**Comment by oleghnidets** [comment]
I close the issue, but if it will be needed I will re-open :)
