### ISSUE TITLE
IPAD3 ver IOS 10.3.3  

### ISSUE THREAD

**Issue by JinhongPark** [oleghnidets/OHMySQL#15]
## What did you do?

iPad 3
IOS 10.3 is the last version.
Apple let go of the iPad 3.

I'm running OHMYSQL on iPad 3.
Here is the phrase:
Warning: Libinfo call to mDNS Responder on mine thread

There is no problem with IOS 11.

I'm trying to develop a SQL monitoring app with version 10.3 of IOS.

IOS10.3 version is also available.

## OHMySQL Environment

- **OHMySQL version: 10.2.2
- **Xcode version: Version 9.4.1 (9F2000)
- **Swift version: 4 (if applicable, if not remove)*
- **Platform(s) running OHMySQL: 

## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.

**Comment by oleghnidets** [comment]
Hi there,
 
It is strange error. Could you, please, provide more details? When does exactly it appear?

**Comment by JinhongPark** [comment]
Thank you for your reply.

I have iPhone x and iPad 3.

The iPhone x is iOS 11.4 version, but there is no problem using it.

But if you test it with iPad 3 (Os version 10.3),
Warning: Libinfo call to mDNS Responder on mine thread
There is an error.

You'll know when you test it.
There is an error bringing us.

I want you to hold on to this error.

details
An error occurs when the sql value is set and the retrun is received in the "let = user" part.

Error: Working: Libinfo call to mDNS Responder on mine thread

Let user = OHMySQLUser (userName: "root", password: "root", servicename: "localhost", dbName: "ohmysql", port: 3306, "rock: A:

**Comment by oleghnidets** [comment]
I close the issue as it seems out-dated. 
Better support is provided on newer version 3.0.0. But minimum supported version is now iOS 14.0.

Feel free to create new issue if needed.

Thanks!
