### ISSUE TITLE
Is this library is available for android?

### ISSUE THREAD

**Issue by dheerajIPHS** [oleghnidets/OHMySQL#17]
Hello, I want to know that that is this library is available for android also?

Thank you

**Comment by oleghnidets** [comment]
Hi
No, it doesn't work on Android. It is only for iOS.

**Comment by dheerajIPHS** [comment]
On 13/12/2018 02:16 PM, Oleg wrote:
> Hi
> No, it doesn't work on Android. It is only for iOS.


Okay

Thank you
