### ISSUE TITLE
Could you please give more documentations for querying?

### ISSUE THREAD

**Issue by estella98** [oleghnidets/OHMySQL#18]
## What did you do?

ℹ I want to query the top 10 rows and wrote the line below:
let query = OHMySQLQueryRequestFactory.select("Info", condition: "LIMIT 10")
        

## What happened instead?
error message:
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LIMIT 10' at line 1"

## What did you expect?
LIMIT 10 is the correct SQL syntax

ℹ Expected results. Please replace this with what you expected.  

## OHMySQL Environment

- **OHMySQL version:**
- **Xcode version:**
- **Swift version:** *(if applicable, if not remove)*
- **Platform(s) running OHMySQL:**

## Demo Project
 
Thank you. It is a good library, I will appreciate more if the documentation is clearer!

ℹ Please link to or upload a project we can download that reproduces the issue.

**Comment by oleghnidets** [comment]
Thanks. I will take a look.

**Comment by oleghnidets** [comment]
Hey there,
Put documentation into [README](https://github.com/oleghnidets/OHMySQL#execute-query), also you may check how does querying work in Samples. 

Thanks!
