### ISSUE TITLE
if Column type is varchar，that data will be null

### ISSUE THREAD

**Issue by Geforceyu** [oleghnidets/OHMySQL#2]
if Column type is varchar，that data will be null

**Comment by oleghnidets** [comment]
I guess it is fixed in [0.3.1beta](https://github.com/oleghnidets/OHMySQL/releases/tag/0.3.1beta). 
I am going to write tests to cover the issue

**Comment by oleghnidets** [comment]
Done in the [latest release](https://github.com/oleghnidets/OHMySQL/releases/tag/1.0.0)
