### ISSUE TITLE
How to use in Swift Project.

### ISSUE THREAD

**Issue by JiekangLiao** [oleghnidets/OHMySQL#21]
## What did you do?

ℹ Please replace this with what you did.  

## What happened instead?

ℹ Actual results. Please replace this with of what happened instead. 

## What did you expect?

ℹ Expected results. Please replace this with what you expected.  

## OHMySQL Environment

- **OHMySQL version:**
- **Xcode version:**
- **Swift version:** *(if applicable, if not remove)*
- **Platform(s) running OHMySQL:**

## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.

**Comment by oleghnidets** [comment]
Hi,
Like in Objective-C.
Take a look at example https://github.com/oleghnidets/OHMySQL/tree/master/SampleProject-Swift-macOS
