### ISSUE TITLE
result is not complete

### ISSUE THREAD

**Issue by cyywhu** [oleghnidets/OHMySQL#25]
## What did you do?

ℹ store and load pictures

## What happened instead?

ℹ Successfully store the picture, but the result is not complete(seems to be sliced) when I load pictures (length is always 86 bytes)

## What did you expect?

ℹ return a complete result when I load pictures

## OHMySQL Environment

- **OHMySQL version:**
- **Xcode version:**11.6
- **Swift version:** *(if applicable, if not remove)*5
- **Platform(s) running OHMySQL:**iOS

## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.

**Comment by oleghnidets** [comment]
Hi @cyywhu ,

Could you, please, provide more details? Do you try to put base64 string into a field? If you can provide steps to reproduce it will help me to investigate the issue.

**Comment by oleghnidets** [comment]
Close the issue as no response provided.
