### ISSUE TITLE
Can't build for MacCatalyst

### ISSUE THREAD

**Issue by yoKurt94** [oleghnidets/OHMySQL#26]
## What did you do?

Building an app supporting MacCatalyst.

## What happened instead?

I get an error when trying to run the app saying "ld: [projectDirectory]Pods/OHMySQL/OHMySQL/lib/ios/libmysqlclient.a(libmysql.o), building for Mac Catalyst, but linking in object file built for iOS Simulator, for architecture x86_64"

## What did you expect?

It should build and run.

## OHMySQL Environment

- **OHMySQL version: **
- **Xcode version: 13.1**
- **Platform(s) running OHMySQL: iOS, MacCatalyst**

**Comment by oleghnidets** [comment]
Hey @yoKurt94 

Please, try 3.0.0 version. It's basedon `xcframework` and supports `Mac Catalyst`.

**Comment by yoKurt94** [comment]
Thank you! I couldn't install it yet since I have no experience in adding pods using zip without using a pod file...

**Comment by oleghnidets** [comment]
Just try to drop [OHMySQL](https://github.com/oleghnidets/OHMySQL/tree/master/OHMySQL) folder into your project.

**Comment by oleghnidets** [comment]
Please, check the latest version. If it doesn't work let me know.
Thanks
