### ISSUE TITLE
Crash when transforming NULL number

### ISSUE THREAD

**Issue by goodman-capu** [oleghnidets/OHMySQL#3]
I came across a crash when it tried to transform an NULL string into an NSNumber

In `OHMySQLSerialization.m`，it lacks null checking of the cString.

```objc
+ (NSNumber *)numberFromCString:(const char *)cString {
    NSString *numberString = [NSString stringWithUTF8String:cString];
    NSNumberFormatter *formatter = [[NSNumberFormatter alloc] init];
    
    return [formatter numberFromString:numberString];
}
```

In console:

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** +[NSString stringWithUTF8String:]: NULL cString'
```

**Comment by goodman-capu** [comment]
Sorry I didn't notice that 1.0.0 version has already released. The code is different as shown above, but I don't know whether the problem still exists. I've updated to 1.0.0 and do some tests.

**Comment by oleghnidets** [comment]
Hi,

No problem. Just check the latest version and, please, let me know. I hope it is fixed.

**Comment by goodman-capu** [comment]
The problem no longer exists : )
