### ISSUE TITLE
[Query] Hardware/Software Support 

### ISSUE THREAD

**Issue by Joechen0121** [oleghnidets/OHMySQL#31]
Hi !

I want to ask some questions about this project.

[Hardware Question]
Is this project available for 2021 Macbook pro M1 chip?

[Software Question]
I have my own MySQL database and access the database using JDBC (Java based).
Now, if I want to use this project to access my MySQL database, could this project work ?

Thanks so much.
BR
JoeChen

**Comment by oleghnidets** [comment]
@Joechen0121 
The library was built on Intel-based Mac. I don't have possibility to build on M1 😢

**Comment by oleghnidets** [comment]
Hi @Joechen0121 
I believe it's fixed already. Otherwise, feel free to reopen the issue. 
Thanks
