### ISSUE TITLE
Insert Image as Blob

### ISSUE THREAD

**Issue by BigityFu** [oleghnidets/OHMySQL#34]
Great Library!
I have a question of the possible Data Types.
Is it possible to send a BLOB? I want to send a Image and haven't find a solution.

Looking forward to your response. 
Thanks so much.

**Comment by oleghnidets** [comment]
Hi @BigityFu 
Did you try to save as a `Data`?

**Comment by oleghnidets** [comment]
Closing as no answer provided.
