### ISSUE TITLE
Disable Debug Logging

### ISSUE THREAD

**Issue by Dirk23** [oleghnidets/OHMySQL#39]
Hi,

is it possible to deactivate the Debug Log when connecting to MySQL Server:
![image](https://user-images.githubusercontent.com/4200682/214847202-c6e2424d-36cc-4ae2-8690-f2f3987501ee.png)

**Comment by oleghnidets** [comment]
Hi
Debug logs exist for debugging purposes, if you would like to not see them you can remove macros `DEBUG` from build settings or introduce new target like `Dev` and not define `DEBUG` flag. 
Note, in `Release` configuration these logs are not present.

**Comment by Dirk23** [comment]
Sorry for my late return on this. I dont know what you mean by "remove macros DEBUG from build settings". Can you please give me a hint what and where to do that?
