### ISSUE TITLE
Provide an escape function

### ISSUE THREAD

**Issue by goodman-capu** [oleghnidets/OHMySQL#4]
The building of query string lacks escaping of special characters. I suggest adding a public function like [this](http://stackoverflow.com/a/6478616) and apply it to `NSString (SQLQueries)` functions.

**Comment by oleghnidets** [comment]
I guess I will use the native MySQL C API functions: [mysql_real_escape_string](https://dev.mysql.com/doc/refman/5.7/en/mysql-real-escape-string.html) and/or [mysql_real_escape_string_quote](https://dev.mysql.com/doc/refman/5.7/en/mysql-real-escape-string-quote.html).

**Comment by oleghnidets** [comment]
Hi there,
Check the latest release. I added a public method -escapedUsingEncoding. Although, I am still in progress due to lack of the time. The next step is applying the method to a query.

**Comment by goodman-capu** [comment]
There are problem with this function: Not every character's length is 2.
For example, if you run this code:
` NSLog(@"%@", [@"'好" escapedUsingEncoding:NSUTF8StringEncoding]);`
The app would crash, for some Chinese characters' length is 3, and for some Emoji it's 4.

**Comment by goodman-capu** [comment]
Opps, my bad. It worked fine.

**Comment by oleghnidets** [comment]
Well, public method added. The developer is responsible to call `-escapedUsingEncoding` if needed (like in MySQL C API [`mysql_real_escape_string()`](https://dev.mysql.com/doc/refman/5.7/en/mysql-real-escape-string.html)). The issue is closed.
