### ISSUE TITLE
Question about auto detect encoding

### ISSUE THREAD

**Issue by goodman-capu** [oleghnidets/OHMySQL#5]
My database's charset is UTF8MB4, when I use OHMySQL to connect to the database, it says:
`[INFO] New character set: utf8`
It seems that it can't tell the difference between different 'kinds' of UTF-8? I get error when try to insert or update emoji into the database. If I manually execute`SET NAMES UTF8MB4` after connected to the database, it will work properly.

It's really a tough task to write an SQL driver😂

**Comment by oleghnidets** [comment]
Hmm... Looks like on UTF-8MB4 is MySQL-specific encoding and iOS can still use UTF-8. 
I will add this encoding to the enum `CharsetEncoding`.
Thanks for reporting ;]

**Comment by oleghnidets** [comment]
Hi there,
Take a look at [release 1.0.2](https://github.com/oleghnidets/OHMySQL/releases/tag/1.0.2).
