### ISSUE TITLE
Bitcode error on Xcode 8

### ISSUE THREAD

**Issue by anoadragon453** [oleghnidets/OHMySQL#6]
Hey there, I'm trying to use your library on Xcode 8 and any attempt at archiving an app bundled with it results in a Bitcode error on the `libmysqlclient.a` binary. The error is as follows:

```
ld: bitcode bundle could not be generated because '.../Pods/OHMySQL/OHMySQL/lib/ios/libmysqlclient.a(libmysql.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture arm64.
```

It seems the `libmysqlclient.a` binary needs to be rebuilt in Xcode >v8, otherwise Archiving will fail. All attempts to disable bitcode in settings have resulted in no changes. I'm currently compiling a new `libmysqlclient.a` binary with Xcode 8 with the hopes to solve this.

Any suggestions or alternative methods would be appreciated, thank you!

**Comment by oleghnidets** [comment]
Hi,
I got it. Looks like I have to re-build with [extra flags](https://medium.com/@heitorburger/static-libraries-frameworks-and-bitcode-6d8f784478a9). 
I will try to do that ASAP. I believe I will be able to do provide a fix till Monday.

Thanks for letting me know.

**Comment by anoadragon453** [comment]
Thanks for the quick response!

**Comment by oleghnidets** [comment]
Hi there,
Hope I fixed that. But before the release, I want to make sure that it works. Develop branch contains the latest changes. 
Could you, please, try it out `pod 'OHMySQL', :git => 'https://github.com/oleghnidets/OHMySQL', :branch => 'develop'` and let me know a result?

**Comment by anoadragon453** [comment]
Yes, it working perfectly now. Thank you!
