### ISSUE TITLE
"setValue:forUndefinedKey" XCODE 9.1, Swift 4

### ISSUE THREAD

**Issue by alihaider525** [oleghnidets/OHMySQL#8]
Hi
I converted my code from swift 3 to swift 4 and updated Xcode version to 9.1 from 8. Now, when i run my application it is giving me this "setValue:forUndefinedKey" error while mapping response to dictionary.

Can you please guide me what can be the possible issues ??

**Comment by oleghnidets** [comment]
Hi,
Hmmm... strange. 
Thanks for reporting. I will take a look ASAP.

**Comment by alihaider525** [comment]
Thanks for your response.

Yeah, sure, here is my debug information:

When i try to map response to my object i.e. 

let patient = Patient()
patient.map(fromResponse: response)

Then following method of NSObject+Mapping.m is called. Everything works fine but when last line of this function executes then it gives this error: "setValue:forUndefinedKey"

- (void)mapFromResponse:(NSDictionary *)response {
    NSParameterAssert(response);
    NSDictionary *mirrorMappingDictionary = [self.mappingDictionary mirror];
    for (NSString *key in mirrorMappingDictionary.allKeys) {
        id value = response[key] == [NSNull null] ? nil : response[key];
        [self setValue:value forKey:mirrorMappingDictionary[key]]; // This line is giving error
    }
}

1. "value" and "mirrorMappingDictionary[key]" both contains non null values but in-spite of this it is throwing the same error and for each column.

2. When i was running this in swift 3 and xcode 8, if value is nil then it was managing this too efficiently but now if value contains nil or not it throws error every time.

Note: Currently i am using Xcode 9.2, Swift 4 and OHMySQL 2.1.1.

**Comment by oleghnidets** [comment]
@alihaider525 Try to add `@objc` attribute before properties you want to map.

**Comment by oleghnidets** [comment]
@alihaider525 Any updates?

**Comment by alihaider525** [comment]
that's amazing, it is working now.

Thanks a lot @oleghnidets for your precious time.

And really sorry for late, i was little busy.

**Comment by alihaider525** [comment]
that's amazing, it is working now. You're great bro. (y)

Thanks a lot @oleghnidets for your precious time.

And really sorry for late, i was little busy.

**Comment by oleghnidets** [comment]
Glad to hear that it works for you.
Thanks 🙂

**Comment by MelissaShu** [comment]
First at all , thank you a lot !
Then I want to ask you a question, after query, I can get correct result number, but the text kind result is null. How to fix it?

**Comment by MelissaShu** [comment]
I have soled this problem by update to the latest version.
Addtionally, when I get  query of type text data, it results NSData not NSString result.

**Comment by oleghnidets** [comment]
Correct, there were major changes and improvements. If you will have the issue let me know.
